services:
  - type: web
    name: telegram-forwarder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tg-drive.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
